# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'camera', :path => '../camera'
  pod 'TensorFlowLiteC', '~> 2.14.0'
  # Pods for iosApp

end
